version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:12
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Install Packages
          command: npm ci
      - run:
          name: Run Lint
          command: npm run lint
workflows:
  version: 2
  test_flow:
    jobs:
      - lint
